mail.app-name=mail-0.0.1
server.port=8097
mail.pool-send-mail-size=1
mail.queue-update-status-size=100001
mail.queue-send-mail-size=100001
mail.listener-test-restart-period=60001
mail.status-update-package-size=101
spring.datasource.url=jdbc:pgsql://fenomy.cc:5432/fenomy
spring.datasource.driver-class-name=com.impossibl.postgres.jdbc.PGDriver
spring.datasource.username=mail_bot
spring.datasource.password=mail_bot

spring.mail.host=smtp.fenomy.com
spring.mail.port=587
spring.mail.username=info@fenomy.com
spring.mail.password=8fT2cgT8tsBDZ5sj
spring.mail.sender.email=info@fenomy.com
spring.mail.sender.text=INFO

spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp

#spring.datasource.url=jdbc:postgresql://fenomy.cc:5432/fenomy
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.com.zaxxer.hikari=warn
logging.level.com.anksystems=debug
logging.level.com.anksystems.fenomy_mail.FenomyMailApplication=debug
logging.level.com.anksystems.fenomy_mail.FenomyMailApplicationKt=debug
logging.file.name=build/tmp/${mail.app-name}.log

#host=smtp.fenomy.com:465
#username=fenomy@fenomy.com
#password=HwUwU09shOZgD6vc
#
#[noreply]
#host=smtp.fenomy.com:465
#username=noreply@fenomy.com
#password=fwjsC3iYhN7y4giM
#
#[support]
#host=smtp.fenomy.com:465
#username=support@fenomy.com
#password=XwlyIFN8FeHTss0Q
#
#[fenomy]
#host=smtp.fenomy.com:465
#username=fenomy@fenomy.com
#password=HwUwU09shOZgD6vc
#
#[alert]
#host=smtp.fenomy.com:465
#username=alert@fenomy.com
#password=jDPStEFvk1aNrGGI
#
#[info]
#host=smtp.fenomy.com:465
#username=info@fenomy.com
#password=8fT2cgT8tsBDZ5sj